### PR TITLE
Add title replacement for describe functions as well

### PR DESCRIPTION
**Pull request by smlgbl**

### CODE REVIEW

**Comment by mjtodd** [comment]
Sorry for the delay in looking at this. Can you please resolve the conflicts, and ideally create a test / update readme to illustrate this change

**Comment by jlutzhbo** [comment]
@mjtodd @smlgbl Any updates on this? Would be really great to have this. Thanks!

**Comment by grawk** [comment]
:+1: and also :+1: to know this module is being looked after at all. I, and others at my company, use it heavily. I would be happy to throw my hat in the ring as a contributor/maintainer if you all are tired of it :)

**Comment by mjtodd** [comment]
Thanks for the feedback @grawk  and offer to contribute. I'm not tired of it, and use it in many projects myself on a daily basis. It's great to hear that others find this useful too.

 I'm assuming @smlgbl isn't going to fix the PR. If you would like to fix the PR, then that help would be greatly appreciated.

**Comment by grawk** [comment]
Awesome! I'll check back in when I've got the PR fixed. Pretty busy this week but would like to see this one through. Thanks again.

**Comment by jlutzhbo** [comment]
@mjtodd @grawk @smlgbl Any hope at getting this in soon? This PR has been open for almost two years :-)

**Pull request closed without merging**
